<?php
?>
<h2>titre de l'enquête</h2>
<h3>Description :</h3>
<p><?php echo'text text text text text text text text text text text text <br>
text text text text text text text text text text text text text <br>
text text text text text text text text text text text text text  <br>
text text text text text text text text text text text text <br>
text text text text text text text text text text text text text <br>
text text text text text text text text text text text text text.  <br>'
?></p>
<div>
<form action="" method="post">
    <label for="">Question < :(Type Texte)</label><br>
        <textarea name="question1" value=""></textarea><br>
    <label for="">Question 2 :(Type Nombre)</label><br>
        <input type="number" name="Question2" value=""/><br>
    <label for="">Question 3 :(Type QCM)nb>=5</label><br>
        <select name="choix">
            <option>choix1</option>
            <option>choix2</option>
            <option>choix3</option>
            <option>choix4</option>
            <option>choix5</option>
            <option>choix6</option>
        </select><br>
    <label for="">Question 3 :(Type QCM)nb<5</label><br>
            <input type="radio" name="proposition" value="Proposition1"/>Proposition1
            <input type="radio" name="proposition" value="Proposition2"/>Proposition2
            <input type="radio" name="proposition" value="Proposition3"/>Proposition3<br>
            <input type="submit" value="Envoyer vos réponses " name="envoyer" /> 
</form> 
</div>