<?php
/* @var $enquete \Application\Entity\Enquete */
/* @var $formEnquete \Application\Form\EnqueteForm */
?>
<h1>Consulter les résultats</h1>

<h2><?php echo $enquete->getTitre(); ?></h2>

<p>Nombre de réponses enregistrées : <?php echo $enquete->getNbReponses(); ?></p>


<?php
for ($i = 0; $i < count($enquete->getListeQuestions()); $i++):

    $question = $enquete->getListeQuestions()[$i]; /* @var $question \Application\Entity\Question */
    $resultat = $enquete->getListeResultats()[$i]; /* @var $resultat \Application\Entity\Resultat */
    ?>

    <p><?php echo $question->getLibelle(); ?></p>

    <table>

    <?php if ($question->getType() == "text") : ?>

            <tr>
                <th>Réponses</th>
            </tr>

        <?php foreach ($resultat->getResultat() as $line): ?>

                <tr>
                    <td><?php echo $line; ?></td>
                </tr>

            <?php endforeach; ?>

    <?php elseif ($question->getType() == "nb") : ?>

            <tr>
                <th colspan="4" >Réponses</th>
            </tr>

            <tr>
                <th>Minimum</th>
                <th>Maximum</th>
                <th>Moyenne</th>
                <th>Somme</th>
            </tr>

            <tr>
                <td><?php echo $resultat->getResultat()['min']; ?></td>
                <td><?php echo $resultat->getResultat()['max']; ?></td>
                <td><?php echo number_format($resultat->getResultat()['moyenne'], 2); ?></td>
                <td><?php echo $resultat->getResultat()['somme']; ?></td>
            </tr>

    <?php elseif ($question->getType() == "qcm") : ?>

            <tr>
                <th colspan="2">Réponses</th>
            </tr>

            <tr>
                <th>Proposition</th>
                <th>Nombre de réponse(s)</th>
            </tr>

        <?php foreach ($resultat->getResultat() as $line): ?>

                <tr>
                    <td><?php echo $line['libelle']; ?></td>
                    <td><?php echo $line['compte']; ?></td>
                </tr>

            <?php endforeach; ?>

    <?php endif; ?>

    </table>

<?php endfor; ?>

<form action="">

    <p>Souhaitez-vous supprimer l'ensemble des données collectées ?</p>

    <input type="submit" value="Envoyer Effacer les données" name="effacer" />

</form>
