<!-- Scripts -->
<?php
//ajout du script dans le head
$this->headScript()->appendFile($this->basePath() . '/js/ajoutQuestion.js');

//ajout du css
$this->headLink()->prependStylesheet($this->basePath() . '/css/ajoutQuestion.css');
?>


<h1>Nouvelle enquête</h1>

<p id="jsrequired">Vous devez activer javascript dans votre navigateur pour pouvoir ajouter une enquête...</p>

<?php echo $this->form()->openTag($formCreation); ?>

<?php echo $this->formLabel($formCreation->get("titre")); ?>
<?php echo $this->formElement($formCreation->get("titre")); ?>

<?php echo $this->formLabel($formCreation->get("description")); ?>
<?php echo $this->formElement($formCreation->get("description")); ?>

<div id="questCont">·
    <div class="question">

        <?php echo $this->formLabel($formCreation->get("question")); ?>
        <?php echo $this->formElement($formCreation->get("question")); ?>

        <?php echo $this->formElement($formCreation->get("suppquest")); ?>

        <?php echo $this->formLabel($formCreation->get("type")); ?>
        <?php echo $this->formElement($formCreation->get("type")); ?>

        <?php echo $this->formLabel($formCreation->get("proposition[]")); ?>
        <?php echo $this->formElement($formCreation->get('ajoutprop')); ?>

        <?php echo $this->formElement($formCreation->get("proposition[]")); ?>
        <?php echo $this->formElement($formCreation->get("proposition[]")); ?>
        
    </div>
</div>

    <?php echo $this->formElement($formCreation->get('ajoutquest')); ?>

<input type="submit" value="enregistrer" />

<?php $this->form()->closeTag(); ?>
