<?php
/**
 * vue partielle liste de requêtes
 */
?>

<?php if($this->flashMessenger()->hasSuccessMessages()) : ?>
<div class="alert alert-success alert-block">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <p><strong>Succès :</strong></p>
  <?php foreach ($this->flashMessenger()->getSuccessMessages() as $message): ?>
    <p><?php echo $message ; ?></p>
  <?php endforeach; ?>
</div>
<?php endif; ?>

<?php if($this->flashMessenger()->hasErrorMessages()) : ?>
<div class="alert alert-error alert-block">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <p><strong>Erreur :</strong></p>
  <?php foreach ($this->flashMessenger()->getErrorMessages() as $message): ?>
    <p><?php echo $message ; ?></p>
  <?php endforeach; ?>
</div>
<?php endif; ?>


<h1>Liste de vos enquêtes</h1>

<table>
    <thead>
        <tr>
            <th>Titre de l'enquête</td>
            <th colspan='4'>Actions</td>
        </tr>
    </thead>
    <tbody>    
        <?php foreach ($enquetes as $enq): /* @var $enq \Application\Entity\Enquete */ ?>
            <tr>
                <td><?php echo $enq->getTitre(); ?></td>
                <td><a href="<?php echo $this->url('voirEnquete', array('id'=>$enq->getId())); ?>">aperçu</a></td>
                <td><a href="<?php echo $this->url('modifierEnquete', array('id'=>$enq->getId())); ?>">éditer</a></td>
                <td><a href="<?php echo $this->url('supprimerEnquete', array('id'=>$enq->getId())); ?>">supprimer</a></td>
                <td><a href="<?php echo $this->url('resultatsEnquete', array('id'=>$enq->getId())); ?>">résultats</a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>

</table>

