<?php

/*
 * vue effacerDonnees
 */
?>


<h3>Suppression de l'enquête <?php echo 'titre'?></h3> 

<p>Voulez vous supprimer l'enquête <?php echo 'titre'?> ?</p>
<p>Attention, cette action est irréversible...</p>


<form method="POST">
<input type="radio" name="suppresion" value="oui"/>oui
<input type="radio" name="suppresion" value="non"/>non</br>
<input type="submit" name="valider" value="valider"/>

</form>
